version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports: 
      - 27017:27017
    networks:
      - go_net
  go-docker:
    container_name: go-docker
    image: app_golang_fix:1.0
    ports:
      - 8080:8080
    networks:
      - go_net
    depends_on: 
      - mongo
    environment:
      - NAME=Hosea
      - SECRET=KAMU_KAMPANG
      - MONGO_CLIENT=mongodb://mongo:27017

networks:
  go_net:
    name: go_net